add debug if
hoverinc/tableau-utilities pull request #29
Opened 2023-03-13 23:36 UTC by jaybythebay

CLI was erroring on 2 issues:
* Not having a default Tableau API Version
* Not having an IF statement before a colored print

2023-03-13 23:43 UTC, jaybythebay commented
@JustinGrilli  a couple of minor bugs

2023-03-14 16:03 UTC, JustinGrilli requested changes
Can you revert the default api_version change, and pull the change I just pushed?
If that change I pushed doesn't fix this, we can troubleshoot from there :)

2023-03-14 16:07 UTC, jaybythebay commented on tableau_utilities/scripts/cli.py
> +group_server_auth.add_argument('--api_version', default='3.18', help='Tableau API version')
@JustinGrilli  your fix did the trick.

Here are 2 other small bug fixes if you want to merge this in.

2023-03-14 16:08 UTC, JustinGrilli approved these changes
Looks good! Thanks Jay!

2023-03-14 16:08 UTC, jaybythebay commented
Thanks to you as well!

2023-03-14 16:09 UTC, merged